steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/artex-81e74/artex-server",
        "-f",
        "Dockerfile",
        ".",
      ]

  # Push the Docker image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/artex-81e74/artex-server"]

  # Deploy the image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "artex-server"
      - "--image"
      - "gcr.io/artex-81e74/artex-server"
      - "--region"
      - "europe-west3"
      - "--platform"
      - "managed"
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY
